[package]
name = "migrations_macros"
version = "1.4.0"
authors = ["Sean Griffin <sean@seantheprogrammer.com>"]
license = "MIT OR Apache-2.0"
description = "Codegeneration macros for diesels embedded migrations"
documentation = "http://docs.diesel.rs"
homepage = "http://diesel.rs"

[dependencies]
migrations_internals = "~1.4.0"
syn = { version = "0.11.4", features = ["aster"] }
quote = "0.3.12"

[dev-dependencies]
tempdir = "0.3.4"

[lib]
proc-macro = true

[features]
default = []
